### ISSUE TITLE
[Header] 헤더 추가 

### ISSUE THREAD

**Issue by JEmilyKoo** [project-eoot/eoot-frontend#8]
## ✏️ 구현 사항

- [x] 헤더 UI 완성
- [x] 헤더와 라우터 링크
- [x] sideBar UI 완성
- [x] 사이드바 라우터 링크 

## 📝 구현 사항 설명

상단의 헤더를 생성합니다.  postWritePage 의 header와는 별개입니다.

**Comment by jaesimin0903** [comment]
good
